.TH "avicap" "1" "12 February 2003" "Zdenek Kabelac" ""
.SH "NAME"
avicap \- v4l capturing and PVR tool
.SH "SYNOPSIS"
.B avicap
.RI [options]\ [ \ files\  | \ URLs\  ]
.SH "DESCRIPTION"
.B avicap

avicap is a video4linux capturing and PVR tool.

avicap can shutdown/poweroff and poweron/reboot your computer again

look here for a full end user documentation on Avicap, its timertable/PVR mode and it's shutdown options:

http://avifile.sourceforge.net/


.SH "OPTIONS"
\fB\-timer\fR
start in automatic timer (PVR) mode
.TP 

.BR 
.SH "SEE ALSO"
\fBaviplay(1)\fR
\fBkv4lsetup(1)\fR

