.TH "avirecompress" "1" "12 February 2003" "Zdenek Kabelac" ""
.SH "NAME"
avirecompress \- video recompression tool
.SH "SYNOPSIS"
.B avirecompress
.RI [options]\ [ \ files\  | \ URLs\  ]
.SH "DESCRIPTION"
.B avirecompress

.SH "OPTIONS"
\fB\-h \-\-help\fR
Show help message
.TP 

.BR 
.SH "SEE ALSO"
\fBaviplay(1)\fR
